#pragma once

#define PCI_SELECT_UPPER_BYTE ~0x00FF
#define PCI_SELECT_LOWER_BYTE 0x00FF
#define PCI_OFFSET_CLASS 0xA
#define PCI_SELECT_ONE_WORD 0xFFFF
#define PCI_SELECT_REGISTER 0xFFFFFFFF
#define INTEL_ETHER_CSR_IO_BASE_REG 20